apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-1
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: sivasai2003/app:latest  # Replace with your actual Docker Hub repo
          ports:
            - containerPort: 80
